import styled from 'styled-components';

const StyledBox = styled.div`
    display: ${props => props.boxDisplay};
    box-shadow: ${props => props.theme.shadow[props.shadow] || props.shadow};
    color: ${props => props.theme.color[props.fontColor] || props.fontColor};
    background-color: ${props => props.theme.color[props.bgColor] || props.bgColor};
    position: ${props => props.pos};
    top: ${props => props.top};
    bottom: ${props => props.bottom};
    left: ${props => props.left};
    right: ${props => props.right};
    width: ${props => props.w};
    height: ${props => props.h};
    min-width: ${props => props.minWidth};
    min-height: ${props => props.minHeight};
    max-width: ${props => props.maxWidth};
    max-height: ${props => props.maxHeight};
    padding: ${props => props.theme.spacing[props.p] || props.p};
    padding-top: ${props => props.theme.spacing[props.pt] || props.pt};
    padding-bottom: ${props => props.theme.spacing[props.pb] || props.pb};
    padding-left: ${props => props.theme.spacing[props.pl] || props.pl};
    padding-right: ${props => props.theme.spacing[props.pr] || props.pr};
    margin: ${props => props.theme.spacing[props.m] || props.m};
    margin-top: ${props => props.theme.spacing[props.mt] || props.mt};
    margin-bottom: ${props => props.theme.spacing[props.mb] || props.mb};
    margin-left: ${props => props.theme.spacing[props.ml] || props.ml};
    margin-right: ${props => props.theme.spacing[props.mr] || props.mr};
    border-style: ${props => props.bs};
    border-width: ${props => props.theme.spacing[props.bw] || props.bw};
    border-color: ${props => props.theme.color[props.bc] || props.bc};
    border-radius: ${props => props.theme.spacing[props.br] || props.br};
    border-top-style: ${props => props.bts};
    border-top-width: ${props => props.theme.spacing[props.btw] || props.btw};
    border-top-color: ${props => props.theme.color[props.btc] || props.btc};
    border-bottom-style: ${props => props.bbs};
    border-bottom-width: ${props => props.theme.spacing[props.bbw] || props.bbw};
    border-bottom-color: ${props => props.theme.color[props.bbc] || props.bbc};
    border-left-style: ${props => props.bls};
    border-left-width: ${props => props.theme.spacing[props.blw] || props.blw};
    border-left-color: ${props => props.theme.color[props.blc] || props.blc};
    border-right-style: ${props => props.brs};
    border-right-width: ${props => props.theme.spacing[props.brw] || props.brw};
    border-right-color: ${props => props.theme.color[props.brc] || props.brc};
    border-top-left-radius: ${props => props.theme.spacing[props.btlr] || props.btlr};
    border-top-right-radius: ${props => props.theme.spacing[props.btrr] || props.btrr};
    border-bottom-left-radius: ${props => props.theme.spacing[props.bblr] || props.bblr};
    border-bottom-right-radius: ${props => props.theme.spacing[props.bbrr] || props.bbrr};
`;

export default StyledBox;
